/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stic3.rh.ui;

import java.awt.List;
import java.sql.Array;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stic3.rh.dao.DepartementBean;
import stic3.rh.mapping.Departement;

/**
 *
 * @author AHMADOU
 */
public class FindallDept extends javax.swing.JInternalFrame {

    /**
     * Creates new form FindallDept
     */
    ArrayList list = null;
    String dept[][] = null;
    Departement dep=null;
    String[] Colonne = new String[3];
    

    public FindallDept() {
        try {
            initComponents();
dep = new Departement();
            Colonne[0] = "Matricule";
            Colonne[1] = "Nom";
            Colonne[2] = "Localite";

            
            // ArrayList list=new ArrayList();
            list = DepartementBean.findAll();
            dept = new String[list.size()][3];
            int i = 0;
             for (Object list1 : list) {
                 dep=(Departement) list1;
            dept[i][0]=dep.getDeptno();
            dept[i][1]=dep.getDname();
            dept[i][2]=dep.getDloc();
             i++;
             }
             depttab.setModel(new DefaultTableModel(dept, Colonne));
        } catch (Exception ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        depttab = new javax.swing.JTable();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        depttab.setAutoCreateRowSorter(true);
        depttab.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 255)));
        depttab.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        depttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deptno", "Dname", "Dloc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depttab.setCellSelectionEnabled(true);
        depttab.setDragEnabled(true);
        jScrollPane2.setViewportView(depttab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        // try {
            /*listdept=DepartementBean.findAll();
         if(!listdept.isEmpty())
         {
         // Object[]  vdept=listdept.toArray();
         /*listDEP.setListData(listdept);
         listDEP.setVisible(true);
         JOptionPane.showMessageDialog(null, " " + listdept.toString(), "Liste Departement", JOptionPane.INFORMATION_MESSAGE);

         }
                  
         } catch (Exception e) {
         }*/
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable depttab;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
