/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stic3.rh.ui;

import javax.swing.JOptionPane;
import stic3.rh.dao.DepartementBean;
import stic3.rh.mapping.Departement;

/**
 *
 * @author AHMADOU
 */
public class FormDept extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDept
     */
    public FormDept() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dname = new javax.swing.JTextField();
        Dloc = new javax.swing.JTextField();
        val_BTN = new javax.swing.JButton();
        anu_BTN = new javax.swing.JButton();

        jLabel1.setText("Nom du Departement");

        jLabel2.setText("Localite ");

        Dname.setName("Dname"); // NOI18N

        Dloc.setName("Dloc"); // NOI18N

        val_BTN.setText("Valider");
        val_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_BTNActionPerformed(evt);
            }
        });

        anu_BTN.setText("Annuler");
        anu_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anu_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(val_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dname)
                            .addComponent(Dloc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(anu_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dloc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(val_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(anu_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void val_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_BTNActionPerformed
        // TODO add your handling code here:
        try {
            Departement dept = new Departement();
        dept.setDloc(Dloc.getText());
        dept.setDname(Dname.getText());
        int i = DepartementBean.addDept(dept);
        if (i != 0) {
            JOptionPane.showMessageDialog(null, "Departement " + Dname.getText() + " ajoute avec succes", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        }
        else
                        JOptionPane.showMessageDialog(null, "erreur", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, "erreur "+ e.getMessage(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);

        }
        

    }//GEN-LAST:event_val_BTNActionPerformed

    private void anu_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anu_BTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_anu_BTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dloc;
    private javax.swing.JTextField Dname;
    private javax.swing.JButton anu_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton val_BTN;
    // End of variables declaration//GEN-END:variables
}
