/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stic3.rh.ui;

import java.text.SimpleDateFormat;
import java.util.*;


import javax.swing.*;

import stic3.rh.dao.DepartementBean;
import stic3.rh.dao.EmployeBean;
import stic3.rh.mapping.Departement;
import stic3.rh.mapping.Employe;

/**
 *
 * @author AHMADOU
 */
public class FormEmp extends javax.swing.JInternalFrame {

    Employe emp,emp1 = null;
    Departement dept = null;
    static ArrayList list = null;

    /**
     * Creates new form FormEmp
     */
    public FormEmp() throws Exception {

        try {
            list = DepartementBean.findAll();
            initComponents();
            for (Object col : list) {
                dept = (Departement) col;
                Dname_CBX.addItem(dept.getDname());
            }
            Dname_CBX.setSelectedIndex(-1);
            Mgr_TBX.setText("");
        } catch (Exception e) {
            throw e;
        }

        //Dname_CBX=new JComboBox((ComboBoxModel) DepartementBean.findAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Empname_TBX = new javax.swing.JTextField();
        Empjob_TBX = new javax.swing.JTextField();
        Empsal_TBX = new javax.swing.JTextField();
        Empom_TBX = new javax.swing.JTextField();
        Val_BTN = new javax.swing.JButton();
        Dname_CBX = new javax.swing.JComboBox();
        Hiredate_TBX = new javax.swing.JTextField();
        Mgr_TBX = new javax.swing.JTextField();
        Ann_BTN = new javax.swing.JButton();

        jLabel2.setText("Nom Employe");

        jLabel3.setText("Job employe");

        jLabel4.setText("Matricule Chef");

        jLabel5.setText("Date d'Embauche");

        jLabel6.setText("Salaire");

        jLabel7.setText("Commission");

        jLabel8.setText("Numero Dept");

        Val_BTN.setText("Valider");
        Val_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Val_BTNActionPerformed(evt);
            }
        });

        Dname_CBX.setActionCommand("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Dname_CBX, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), Dname_CBX, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        Dname_CBX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Dname_CBXItemStateChanged(evt);
            }
        });
        Dname_CBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dname_CBXActionPerformed(evt);
            }
        });

        Mgr_TBX.setEditable(false);

        Ann_BTN.setText("Annuler");
        Ann_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ann_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(80, 80, 80))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(77, 77, 77)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(75, 75, 75)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Empjob_TBX)
                                .addComponent(Empname_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mgr_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Dname_CBX, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE)
                            .addComponent(Empom_TBX, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Empsal_TBX, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hiredate_TBX, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Val_BTN)
                        .addGap(96, 96, 96)
                        .addComponent(Ann_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Hiredate_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Empsal_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Empom_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Empname_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Empjob_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Mgr_TBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Dname_CBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Val_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ann_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Val_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Val_BTNActionPerformed
        // TODO add your handling code here:
        
        try {
             emp1 = new Employe();
            emp1.setEmpname(Empname_TBX.getText());
            //emp.setComm( Empom_TBX.getText());
            
            emp1.setJob(Empjob_TBX.getText());
            emp1.setDeptno(dept.getDeptno());
            emp1.setMgr(emp.getEmpno());
            emp1.setComm(Integer.parseInt(Empom_TBX.getText()));
            emp1.setSal(Integer.parseInt(Empsal_TBX.getText()));
            emp1.setHiredate( Hiredate_TBX.getText());
            int i = EmployeBean.addEmp(emp1);
            if (i != 0) {
                JOptionPane.showMessageDialog(null, emp1.getEmpname() + " a ete bien enegistre dans la base ", "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null," erreur khjkhj " + e.getMessage(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);

        }
//if( Pattern.matches(Hiredate_TBX.getText(),)    )
        {

        }
    }//GEN-LAST:event_Val_BTNActionPerformed

    private void Dname_CBXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Dname_CBXItemStateChanged
        // TODO add your handling code here:
        //evt.getItem().toString()
        //JOptionPane.showMessageDialog(null, "Login ou Password Incorrect!" + Dname_CBX.getSelectedObjects().toString(), "Gestion Employe", JOptionPane.INFORMATION_MESSAGE);
        try {

            for (Object col : list) {
                dept = (Departement) col;
                if (dept.getDname() == Dname_CBX.getSelectedItem().toString()) {
                    emp = EmployeBean.findEmp(dept.getDeptno());
                    Mgr_TBX.setText(emp.getEmpname());
                    emp1.setDeptno(dept.getDeptno());
                }

                //Dname_CBX.addItem(dept.getDname());
            }
            //emp = EmployeBean.findEmp(Dname_CBX.getSelectedItem().toString());

            //evt.getSource().
        } catch (Exception ex) {
            //Logger.getLogger(FormEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Dname_CBXItemStateChanged

    private void Dname_CBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dname_CBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dname_CBXActionPerformed

    private void Ann_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ann_BTNActionPerformed
        // TODO add your handling code here:
         //System.exit(1);
        FormEmp.this.dispose();
    }//GEN-LAST:event_Ann_BTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ann_BTN;
    private javax.swing.JComboBox Dname_CBX;
    private javax.swing.JTextField Empjob_TBX;
    private javax.swing.JTextField Empname_TBX;
    private javax.swing.JTextField Empom_TBX;
    private javax.swing.JTextField Empsal_TBX;
    private javax.swing.JTextField Hiredate_TBX;
    private javax.swing.JTextField Mgr_TBX;
    private javax.swing.JButton Val_BTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
